module.exports = {
  singleQuote: true,
  printWidth: 80,
  trailingComma: 'all',
  importOrder: [
    'src/logger/newRelic',
    '^(lodash|react)',
    '@vymo/ui',
    'xstate/react',
    '@vis.gl',
    '@cyntler/react-doc-viewer',
    '@dnd-kit/',
    '@reduxjs/toolkit',
    '@growthbook/growthbook',
    '@monaco-editor/react',
    '@storybook/react',
    '@storybook/test',
    '@testing-library/react',
    'cypress',
    '^(?!react)\\w+$',
    '<THIRD_PARTY_MODULES>',
    '@welldone-software',
    'prettier/standalone',
    '^src|^@(pages|components|hooks|i18n)/?(.*)$',
    '([./])+((?!(css|scss|less)).)*$',
    '[.](css|scss|less)$',
  ],

  plugins: [require.resolve('@trivago/prettier-plugin-sort-imports')],
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
  importOrderCaseInsensitive: true,
  importOrderParserPlugins: ['jsx', 'typescript'],
};
