import { ColumnConfig } from '../types';

export const columns: ColumnConfig[] = [
  {
    name: 'First Name',
    title: 'First Name',
    field: 'First Name',
    type: 'string',
    canSort: true,
    defaultSort: 'desc',
  },
  {
    name: 'Last Name',
    title: 'Last Name',
    field: 'Last Name',
    type: 'string',
    canSort: true,
    defaultSort: '',
  },
  {
    name: 'Age',
    title: 'Age',
    field: 'Age',
    type: 'string',
    canSort: false,
    defaultSort: '',
  },
  {
    name: 'Visits',
    title: 'Visits',
    field: 'Visits',
    type: 'string',
    canSort: false,
    defaultSort: '',
  },
  {
    name: 'Status',
    title: 'Status',
    field: 'Status',
    type: 'string',
    canSort: true,
    defaultSort: '',
  },
  {
    name: 'Progress',
    field: 'Progress',
    title: 'Progress',
    type: 'string',
    canSort: false,
    defaultSort: '',
  },
];

export const data = [
  {
    'First Name': 'Tanner',
    'Last Name': 'Linsley',
    Age: 33,
    Visits: 100,
    Progress: 50,
    Status: 'Married',
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'Vandy',
    Age: 27,
    Visits: 200,
    Progress: 100,
    Status: 'Single',
  },
  {
    'First Name': 'Alice',
    'Last Name': 'Smith',
    Age: 79,
    Visits: 281,
    Progress: 94,
    Status: 'Married',
  },
  {
    'First Name': 'John',
    'Last Name': 'Jones',
    Age: 30,
    Visits: 73,
    Progress: 63,
    Status: 'Divorced',
  },
  {
    'First Name': 'Alice',
    'Last Name': 'Garcia',
    Age: 67,
    Visits: 140,
    Progress: 71,
    Status: 'Single',
  },
  {
    'First Name': 'James',
    'Last Name': 'Davis',
    Age: 52,
    Visits: 496,
    Progress: 4,
    Status: 'Widowed',
  },
  {
    'First Name': 'Maria',
    'Last Name': 'Brown',
    Age: 42,
    Visits: 71,
    Progress: 17,
    Status: 'Divorced',
  },
  {
    'First Name': 'Barbara',
    'Last Name': 'Williams',
    Age: 80,
    Visits: 7,
    Progress: 50,
    Status: 'Widowed',
  },
  {
    'First Name': 'John',
    'Last Name': 'Johnson',
    Age: 35,
    Visits: 310,
    Progress: 33,
    Status: 'Married',
  },
  {
    'First Name': 'Linda',
    'Last Name': 'Jones',
    Age: 24,
    Visits: 295,
    Progress: 47,
    Status: 'Single',
  },
  {
    'First Name': 'Patricia',
    'Last Name': 'Martinez',
    Age: 48,
    Visits: 462,
    Progress: 96,
    Status: 'Widowed',
  },
  {
    'First Name': 'Robert',
    'Last Name': 'Miller',
    Age: 46,
    Visits: 354,
    Progress: 39,
    Status: 'Married',
  },
  {
    'First Name': 'Michael',
    'Last Name': 'Smith',
    Age: 64,
    Visits: 243,
    Progress: 22,
    Status: 'Single',
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'Garcia',
    Age: 71,
    Visits: 190,
    Progress: 67,
    Status: 'Divorced',
  },
  {
    'First Name': 'Alice',
    'Last Name': 'Johnson',
    Age: 27,
    Visits: 120,
    Progress: 9,
    Status: 'Widowed',
  },
  {
    'First Name': 'James',
    'Last Name': 'Davis',
    Age: 77,
    Visits: 488,
    Progress: 86,
    Status: 'Single',
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'Williams',
    Age: 40,
    Visits: 351,
    Progress: 55,
    Status: 'Married',
  },
  {
    'First Name': 'Maria',
    'Last Name': 'Martinez',
    Age: 58,
    Visits: 50,
    Progress: 27,
    Status: 'Divorced',
  },
  {
    'First Name': 'Robert',
    'Last Name': 'Jones',
    Age: 19,
    Visits: 337,
    Progress: 20,
    Status: 'Married',
  },
  {
    'First Name': 'Barbara',
    'Last Name': 'Miller',
    Age: 62,
    Visits: 118,
    Progress: 5,
    Status: 'Single',
  },
  {
    'First Name': 'Linda',
    'Last Name': 'Smith',
    Age: 39,
    Visits: 124,
    Progress: 99,
    Status: 'Widowed',
  },
  {
    'First Name': 'Michael',
    'Last Name': 'Johnson',
    Age: 32,
    Visits: 478,
    Progress: 15,
    Status: 'Divorced',
  },
  {
    'First Name': 'Patricia',
    'Last Name': 'Brown',
    Age: 66,
    Visits: 488,
    Progress: 40,
    Status: 'Married',
  },
  {
    'First Name': 'James',
    'Last Name': 'Garcia',
    Age: 59,
    Visits: 469,
    Progress: 56,
    Status: 'Divorced',
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'Jones',
    Age: 36,
    Visits: 97,
    Progress: 8,
    Status: 'Single',
  },
  {
    'First Name': 'Alice',
    'Last Name': 'Davis',
    Age: 22,
    Visits: 28,
    Progress: 30,
    Status: 'Single',
  },
  {
    'First Name': 'John',
    'Last Name': 'Martinez',
    Age: 26,
    Visits: 424,
    Progress: 84,
    Status: 'Widowed',
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'Smith',
    Age: 54,
    Visits: 129,
    Progress: 24,
    Status: 'Married',
  },
  {
    'First Name': 'Maria',
    'Last Name': 'Johnson',
    Age: 50,
    Visits: 387,
    Progress: 25,
    Status: 'Divorced',
  },
  {
    'First Name': 'Linda',
    'Last Name': 'Brown',
    Age: 41,
    Visits: 43,
    Progress: 66,
    Status: 'Single',
  },
];
