export const userData = {
  isTerritoryUser: false,
  isAdmin: false,
  ssAccess: false,
  created_date: '2024-09-13T15:34:37.434Z',
  code: '1004',
  name: 'Digvijay Dey',
  designation: 'Manager',
  email: 'digvijay@abcapital.com',
  phone: '+919611435849',
  region: '1004',
  roles: [],
  validated: {
    phone: false,
    email: false,
  },
  location_skip_count: 0,
  verification: {
    force_reset_password: false,
    time: '2024-09-13T15:34:37.420Z',
    email_skip: 0,
    phone_skip: 0,
  },
  location_tag_codes: [],
  attributes: {
    phone: '+919611435849',
    type: 'branch',
    profile_photo:
      '{"media_type":"photo","items":[{"bucket":"vymo-uploads-staging","filename":"edea6118-183d-4598-a8a6-c2d90bb77878-k2fZGmf7fL.jpeg","mime":"image/jpeg","label":"profileName","path":"lms/abcapital/1004/edea6118-183d-4598-a8a6-c2d90bb77878-k2fZGmf7fL.jpeg"}],"bucket":"vymo-uploads-staging"}',
    staff_code: '1022',
    no_of_li_branches: '',
    li_branch_city: '',
    li_serviceable_pincode: '',
    designation_code: 'POS',
    manager_mobile_number: '9819100008',
    vymo_user_channel: '[{"name":"ALL","code":"ALL"}]',
    manager_name: 'Harish V',
    branch_pincode: '560012',
    role: 'Distributor',
    function: '',
    sub_function: '',
    employee_zone: '',
    adid: '',
    cost_code: '',
    employee_type: '',
    partner_id: '',
    lg_code: '',
    lf_code: '',
    esb_status: '',
    ing_channel: '',
    microsite_url: 'www.google.com',
    kyd_done: 'No',
    entity: '[{"name":"ABSLI","code":"absli"}]',
    parent_golden_id: '',
    alternate_email: '',
    languages_known: '[]',
    self_serve_roles: '[]',
    code: '1004',
    golden_id: '9611',
    title: 'Mr.',
    first_name: 'Digvijay',
    middle_name: '',
    last_name: 'Dey',
    user_email: 'digvijay.dey@getvymo.com',
    email: 'digvijay@abcapital.com',
    user_pan: 'AOLPD5473L',
    constitution_type: 'Single',
    select_id: '123',
    select_flag: 'Yes',
    auth_type: 'VYMO_LOGIN',
    parent: '100',
    manager_code: '20',
    manager_designation: 'Manager',
    manager_email_id: 'harish@abcapital.com',
    channel_department: 'Banca',
    subchannel_subdepartment: 'banca2',
    designation_name: 'Distributor',
    persona: '[{"code":"seller","name":"Seller"}]',
    user_status: 'Active',
    vintage: '< 6 months',
    fls_category: '',
    kyd_available: 'Yes',
    kyd_valid: 'Yes',
    branch_code: '123',
    branch_name: 'hdfc',
    branch_address: '611| 2nd Block| 3rd Cross| Bangalore 560034',
    date_of_joining: '946684800000',
    sales_panda_user: 'Yes',
    gstn: 'FCMPS09125V',
    select_level: 'Preferred',
    select_tier: 'Preferred',
    family_flag: 'True',
    license_type: 'EXTERNAL',
    user_gender: 'M',
    dob: '946684800000',
    anniversary: '',
    address: 'D107| Oakwood Plaza',
    permanent_address_line_2: 'Road Link',
    pincode: '560093',
    area: 'HSR Layout',
    landmark: '',
    city: 'Bangalore',
    district: 'Karnataka',
    state: 'Karnataka',
    preferred_language_of_communication: 'English',
    date_of_birth_spouse: '',
    date_of_birth_child1: '',
    date_of_birth_child2: '',
    facebook_id: 'http://a.facebook.com',
    twitter_id: 'https://b.twitter.com',
    linkedin_id: 'http://c.linkedin.com',
    licensed: 'Yes',
    name: 'Digvijay Dey',
    entity_codes: '[null,null]',
    client_source: 'Web',
  },
  ftuj_map: {
    search: true,
    intro: true,
    '': true,
    nearby_ftuj: true,
    leadFtuj: true,
  },
  region_hierarchy: [
    'all',
    'SELFSERVE_ADMIN',
    'ABFL211',
    'ABFL213',
    'ABFL212',
    'ABFL214',
    '100',
    '1065',
    '1004',
  ],
  manager: '1065',
  remote_info: {},
  authorised_group_regions: [
    'g_product_posp_and_ulip_disable',
    'g_product_posp_enable_ulip_disable',
    'g_branch_code_123',
  ],
  language: '',
  profile_photo_s3_link:
    'https://vymo-uploads-staging.s3.amazonaws.com/lms/abcapital/1004/edea6118-183d-4598-a8a6-c2d90bb77878-k2fZGmf7fL.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIASWADCQKWXAFCDAXP%2F20241108%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20241108T075217Z&X-Amz-Expires=604800&X-Amz-Signature=a9104ed3c6631f8d2cc4c3c8488acf2411103806f7df69f5ccd17d1335b7c8a7&X-Amz-SignedHeaders=host',
};
export const userProfileGroups = {
  groups: [
    {
      code: 'personal_details',
      name: 'Personal Details',
      category: [
        {
          name: 'My Website',
          code: 'my_website',
          type: 'website',
        },
        {
          name: 'My Bank Details',
          code: 'my_bank_details',
          type: 'grouping_view',
        },
        {
          name: 'Nominee',
          code: 'nominee',
          type: 'grouping_view',
        },
        {
          name: 'My Linked Accounts',
          code: 'linked_accounts',
          type: 'grouping_view',
        },
      ],
    },
    {
      code: 'general',
      name: 'General',
      category: [
        {
          name: 'Connect with Team',
          code: 'contact_details',
          type: 'input_list_view',
        },
      ],
    },
    {
      code: 'help_and_support',
      name: 'Help',
      category: [
        {
          name: 'Help & Support',
          code: 'help_support',
          type: 'grouping_view',
        },
      ],
    },
  ],
};
